language: haskell-stack

git:
  submodules: false

meta:
  before_install:
    prefix:
      - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
      - git submodule update --init

env:
  - GHCVER=7.8.4 STACK_YAML=stack-lts-2.yaml
  - GHCVER=7.10.2 STACK_YAML=stack-lts-3.yaml PEDANTIC=YES

matrix:
  fast_finish: true

branches:
  only:
    - master
